openapi: 3.0.2
info:
  title: Monolithic API POC
  version: 1.0.0
  description: Monolithic API POC
paths:
  /channels:
    summary: channels
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/channel'
        required: true
      tags:
        - channels
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/channel'
          description: '200'
      summary: update
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/channel'
        required: true
      tags:
        - channels
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/channel'
          description: '200'
      summary: create
  '/channels/{channelId}':
    summary: channelId
    parameters:
      -
        name: channelId
        in: path
        required: true
  /users:
    summary: users
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/channel'
        required: true
      tags:
        - users
      responses:
        '200':
          description: '200'
      summary: create
  '/users/{userId}': {}
  /videos:
    summary: videos
    servers:
      -
        url: 'http://localhost:8081'
        description: development
    get:
      tags:
        - videos
      parameters:
        -
          name: categories
          description: ''
          schema:
            type: array
            items:
              type: string
          in: query
        -
          name: pageSize
          description: ''
          schema:
            type: integer
          in: query
          required: true
        -
          name: pageNumber
          description: ''
          schema:
            type: integer
          in: query
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListVideoResponse'
          description: '200'
      security:
        -
          token: []
          oAuth2: []
      summary: List
      description: list of Videos
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/videoRequest'
        required: true
      tags:
        - videos
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/videoRequest'
          description: '201'
      security:
        -
          token: []
      summary: update
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/initiateVideo'
        required: true
      tags:
        - videos
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/initiateVideo'
          description: created
        '400':
          description: '400'
        '401':
          description: '401'
      security:
        -
          token: []
      summary: create
  '/videos/{videoId}':
    get:
      tags:
        - videos
      parameters:
        -
          name: videoId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/videoRequest'
          description: '200'
      summary: Get
  '/videos/{videoId}/comments':
    summary: videos.comments
    get:
      tags:
        - videos.comments
      parameters:
        -
          name: videoId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCommentsResponse'
          description: '200'
      summary: List
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/comment'
        required: true
      tags:
        - videos.comments
      parameters:
        -
          name: videoId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          description: '200'
      summary: Create
  '/videos/{videoId}/comments/{commentId}':
    get:
      tags:
        - videos.comments
      parameters:
        -
          name: videoId
          schema:
            type: string
          in: path
          required: true
        -
          name: commentId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
          description: '200'
      summary: GET
    delete:
      tags:
        - videos.comments
      parameters:
        -
          name: videoId
          schema:
            type: string
          in: path
          required: true
        -
          name: commentId
          schema:
            type: string
          in: path
          required: true
      responses:
        '200':
          description: '200'
      summary: Delete
  '/videos/{videoId}/upload':
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
        required: true
      tags:
        - videos
      responses:
        '201':
          description: '201'
      summary: upload
    parameters:
      -
        name: videoId
        schema:
          type: string
        in: path
        required: true
components:
  schemas:
    videoRequest:
      description: ''
      type: object
      allOf:
        -
          required:
            - tumbnails
            - visibility
          type: object
          properties:
            tumbnails:
              description: thumbails
              maxItems: 3
              minItems: 1
              uniqueItems: true
              type: array
              items:
                format: byte
                type: string
            visibility:
              description: ''
              enum:
                - PUBLIC
                - PRIVATE
                - UNLISTED
              type: string
              readOnly: true
        -
          $ref: '#/components/schemas/initiateVideo'
    initiateVideo:
      description: initiate a video
      required:
        - title
        - videoId
        - channelId
      type: object
      properties:
        title:
          description: video
          maxLength: 256
          minLength: 16
          type: string
        videoId:
          description: ''
          type: string
          readOnly: true
        channelId:
          description: ''
          type: string
          readOnly: false
      example: uuid
    EducationChannel:
      description: ''
      type: object
      allOf:
        -
          required:
            - instituationName
            - registeredAddress
            - website
            - channelType
          type: object
          properties:
            instituationName:
              description: ''
              type: string
            registeredAddress:
              description: ''
              maxLength: 100
              type: string
            website:
              description: ''
              maxLength: 50
              type: string
            channelType:
              description: ''
              type: string
        -
          $ref: '#/components/schemas/videoChannel'
    EntertainmentChannel:
      description: ''
      type: object
      allOf:
        -
          required:
            - address
            - channelType
          type: object
          properties:
            address:
              description: ''
              type: string
            channelType:
              description: ''
              type: string
        -
          $ref: '#/components/schemas/videoChannel'
    channel:
      oneOf:
        -
          $ref: '#/components/schemas/EducationChannel'
        -
          $ref: '#/components/schemas/EntertainmentChannel'
      discriminator:
        propertyName: channelType
      description: ''
      type: object
    videoChannel:
      description: ''
      required:
        - name
        - channelType
        - userId
      type: object
      properties:
        name:
          description: ''
          type: string
        channelType:
          description: ''
          enum:
            - EDUCATION
            - ENTERTAINMENT
          type: string
        userId:
          description: ''
          type: string
    ListVideoResponse:
      description: ''
      required:
        - data
        - PageSize
        - pageNumber
      type: object
      properties:
        data:
          description: requested List
          maxItems: 50
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/videoRequest'
          readOnly: true
        PageSize:
          description: ''
          type: integer
        pageNumber:
          description: ''
          type: integer
      example:
        -
          data:
            - {}
            - {}
          PageSize: 51
          pageNumber: 76
    ListCommentsResponse:
      description: ''
      required:
        - pageNumber
        - pageSize
        - data
      type: object
      properties:
        pageNumber:
          description: ''
          type: integer
        pageSize:
          description: ''
          type: integer
        data:
          description: ''
          type: array
          items:
            $ref: '#/components/schemas/comment'
    comment:
      description: ''
      required:
        - commentId
        - content
      type: object
      properties:
        commentId:
          description: ''
          type: string
        content:
          description: ''
          type: string
  securitySchemes:
    token:
      scheme: bearer
      type: http
    oAuth2:
      flows:
        authorizationCode:
          authorizationUrl: 'http://mysevice/auth'
          tokenUrl: 'http://mysevice/auth1'
          refreshUrl: 'http://mysevice/auth2'
          scopes:
            scope-1: ''
            scope-2: ''
      type: oauth2
